services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_DEFAULT_PORT=5678
    restart: always
    volumes:
      - ./n8n_workflows:/root/.n8n

  pitch-deck-agents:
    build:
      context: .
    container_name: pitch_deck_agents
    env_file:
      - .env
    depends_on:
      - redis
      - n8n
    volumes:
      - ./pitch_deck_data:/app/pitch_deck_data
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "5001:5000"
    command: ["python", "crewai_agents/pitch_deck_crew.py"]

  dashboard:
    build:
      context: .
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_dashboard:/app
    depends_on:
      - pitch-deck-agents
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["streamlit", "run", "streamlit_dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]

networks:
  default:
    driver: bridge