services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_DEFAULT_PORT=5678
    restart: always
    volumes:
      - ./n8n_workflows:/root/.n8n

  pitch-deck-agents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pitch_deck_agents
    depends_on:
      n8n:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5001:5000"

  dashboard:
    build:
      context: ./streamlit_dashboard
      dockerfile: Dockerfile
    container_name: streamlit_dashboard
    depends_on:
      pitch-deck-agents:
        condition: service_healthy
        required: true
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_dashboard:/app
    command: ["streamlit", "run", "app.py"]

networks:
  default:
    driver: bridge